package com.p5m.me.remote_config;

public class RemoteConfigConst {

    public static final String SEARCH_TEXT = "SearchBarText";
    public static final String BOOK_BUTTON = "BookButton";
    public static final String BOOK_BUTTON_COLOR = "BookButtonColor";
    public static final String BOOK_IN_CLASS = "BookInClassProfile";
    public static final String BOOK_WITH_FRIEND = "BookWithFriend";
    public static final String BOOK_IN_CLASS_COLOR = "BookInClassProfileColor";
    public static final String BOOK_WITH_FRIEND_COLOR = "BookWithFriendColor";
    public static final String BOOK_WITH_FRIEND_BACKGROUND_COLOR = "BookWithFriendBGColor";
    public static final String BOOKED_BUTTON = "BookedButton";
    public static final String FULL_BUTTON = "FullButton";
    public static final String WAITLIST_BUTTON = "WAITLIST_BUTTON";
    public static final String WAITLISTED_BUTTON = "WAITLISTED_BUTTON";
    public static final String FULL_BUTTON_COLOR = "FullButtonColor";
    public static final String BOOKED_BUTTON_COLOR = "BookedButtonColor";
    public static final String BUY_CLASS_BUTTON_COLOR = "buyClassButtonColor";
    public static final String BUY_CLASS = "buyClasses";
    public static final String CLASS_CARD_TEXT = "CLASS_CARD_TEXT";
    public static final String RECOMMENDED_FOR_YOU = "Recommended_For_You";
    public static final String RECOMMENDED_FOR_YOU_COLOR = "RECOMMENDED_FOR_YOU_COLOR";
    public static final String SESSION_EXPIRED = "SESSION_EXPIRED";
    public static final String SESSION_EXPIRED_COLOR = "SESSION_EXPIRED_COLOR";
    public static final String INVITE_FRIENDS = "INVITE_FRIENDS";
    public static final String ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
    public static final String JOIN_WAITLIST = "JOIN_WAITLIST";
    public static final String PAYMENT_PACKAGE = "PAYMENT_PACKAGE";
    public static final String PAYMENT_PENDING = "PAYMENT_PENDING";
    public static final String PAYMENT_FAILURE = "PAYMENT_FAILURE";
    public static final String PAYMENT_CLASS = "PAYMENT_CLASS";
    public static final String GYM_VISIT_LIMIT_TEXT = "GYM_VISIT_LIMIT_TEXT";
    public static final String SELECT_PLAN_TEXT = "SELECT_PLAN_TEXT";
    public static final String SELECT_PLAN_COLOR = "SELECT_PLAN_COLOR";
    public static final String GYM_VISIT_LIMIT_DETAIL_TEXT = "GYM_VISIT_LIMIT_DETAIL_TEXT";
    public static final String MEMBERSHIP_OFFER_COLOR = "MEMBERSHIP_OFFER_COLOR";
    public static final String TESTIMONIALS = "testimonials";
    public static final String TESTIMONIALS_RIYADH = "testimonials_riyadh";
    public static final String FAQ = "faqs";
    public static final String PACKAGE_TAGS = "package_tags";
    public static final String WELCOME_P5M = "Welcome_title";
    public static final String WELCOME_P5M_CONTAIN = "Welcome_sub";
    public static final String SECTION_ONE_TITLE = "Section_one_title";
    public static final String SECTION_ONE_SUB_ONE = "Section_one_sub_one";
    public static final String SECTION_ONE_SUB_ONE_CONTAIN = "Section_one_sub_one_detail";
    public static final String SECTION_ONE_SUB_TWO = "Section_one_sub_two";
    public static final String SECTION_ONE_SUB_TWO_CONTAIN = "Section_one_sub_two_detail";
    public static final String SECTION_ONE_SUB_THREE = "Section_one_sub_three";
    public static final String SECTION_ONE_SUB_THREE_DETAIL = "Section_one_sub_three_detail";
    public static final String SECTION_ONE_SUB_FOUR = "Section_one_sub_four";
    public static final String SECTION_ONE_SUB_FOUR_DETAIL = "Section_one_sub_four_detail";
    public static final String SECTION_TWO_TITLE = "Section_two_title";
    public static final String SECTION_TWO_SUB_ONE = "Section_two_sub_one";
    public static final String SECTION_TWO_SUB_ONE_DETAIL = "Section_two_sub_one_detail";
    public static final String SECTION_TWO_SUB_TWO = "Section_two_sub_two";
    public static final String SECTION_TWO_SUB_TWO_DETAIL = "Section_two_sub_two_detail";
    public static final String SECTION_TWO_SUB_THREE = "Section_two_sub_three";
    public static final String SECTION_TWO_SUB_THREE_DETAIL = "Section_two_sub_three_detail";
    public static final String SECTION_TWO_SUB_FOUR = "Section_two_sub_four";
    public static final String SECTION_TWO_SUB_FOUR_DETAIL = "Section_two_sub_four_detail";
    public static final String PLAN_CLASS_TEXT = "plan_class_text";
    public static String PLAN_DESCRIPTION = "plan_description";
    public static String DROP_IN_COST = "drop_in_cost";
    public static String SHOW_SELECTION_OPTIONS = "show_select_options";
    public static String PLAN_DESCRIPTION_DROP_IN = "drop_in_description";
    public static String ON_BOARDING_DATA = "onboarding";
    public static String CHANNEL_KEY = "channels";
    public static String CALL_FINISH_MESSAGE="call_finish_message";
    public static String CALL_FINISH_BUTTON_TITLE="call_finish_button_title";
    public static String YOUTUBE_SECTION_TITLE="youtube_section_title";
    public static String YOUTUBE_SECTION_SUB_TITLE="youtube_section_subtitle";
    public static String YOUTUBE_PLAYLIST_ID="play_list_id";
    public static String LEFT_EARLY_GOOGLE_FORM="left_early_google_form";
    public static String FINISHED_GOOGLE_FORM="finish_google_form";
    public static String CALL_FINISHED_TITLE="call_finish_title";
    public static String BOOK_FIND_CLASS="book_button_find_class";
    public static String BOOK_OTHERS="book_button_other";
    public static String HOW_IT_WORKS="how_it_works";
    public static String CREDIT_VALUE_MODEL = "credit_values_model";
    public static String PHYSICAL_CLASS_VALUE = "physical_class_value";
    public static String VIRTUAL_CLASS_VALUE = "virtual_class_value";
    public static String CONVERSTION_TEXT = "conversion_text";
    public static String PRICE_MODEL = "price_model";
    public static String CREDIT_INFO = "credits_info";
    public static String SPECIAL_INFO = "special_info";
    public static String SPECIAL_PROGRAM_POPUP = "special_program_popup";
    public static String SAFTEY_REMARK_OPTIONS = "safety_remark_options";
    public static String SUBSCRIPTION_CONFIG_VALUE = "subscription_config_values";










    /*------KEY VALUES------*/
    public static final int BOOKED_BUTTON_KEY = 927;
    public static final int FULL_BUTTON_KEY = 928;
    public static final int BOOK_BUTTON_KEY = 929;
    public static final int BOOKED_BUTTON_COLOR_KEY = 930;
    public static final int FULL_BUTTON_COLOR_KEY = 931;
    public static final int BOOK_BUTTON_COLOR_KEY = 932;
    public static final int BOOK_WITH_FRIEND_BUTTON_KEY = 933;
    public static final int BOOK_IN_CLASS_PROFILE_KEY = 934;
    public static final int SEARCH_BAR_TEXT_KEY = 935;
    public static final int CLASS_CARD_TEXT_KEY = 936;
    public static final int RECOMMENDED_FOR_YOU_KEY = 937;
    public static final int BUY_CLASS_KEY = 938;
    public static final int BUY_CLASS_COLOR_KEY = 939;
    public static final int RECOMMENDED_FOR_YOU_COLOR_KEY = 940;
    public static final int BOOK_WITH_FRIEND_COLOR_KEY = 941;
    public static final int SESSION_EXPIRED_KEY = 942;
    public static final int SESSION_EXPIRED_COLOR_KEY = 943;
    public static final int INVITE_FRIENDS_KEY = 944;
    public static final int ADD_TO_WISHLIST_KEY = 945;
    public static final int PAYMENT_PACKAGE_KEY = 946;
    public static final int PAYMENT_PENDING_KEY = 947;
    public static final int PAYMENT_FAILURE_KEY = 948;
    public static final int PAYMENT_CLASS_KEY = 949;
    public static final int GYM_VISIT_LIMIT_KEY = 950;
    public static final int SELECT_PLAN_TEXT_KEY = 951;
    public static final int SELECT_PLAN_COLOR_KEY = 952;
    public static final int GYM_VISIT_LIMIT_DETAIL_TEXT_KEY = 953;
    public static final int MEMBERSHIP_OFFER_COLOR_KEY = 954;
    public static final int BOOK_IN_CLASS_COLOR_KEY = 955;
    public static final int WAITLIST_BUTTON_KEY = 956;
    public static final int WAITLISTED_BUTTON_KEY = 957;
    public static final int JOIN_WAITLIST_KEY = 958;
    public static final int TESTIMONIALS_KEY = 959;
    public static final int FAQ_KEY = 960;
    public static final int PACKAGE_TAGS_KEY = 961;
    public static final int BOOK_WITH_FRIEND_BACKGROUND_COLOR_KEY = 962;
    public static final int WELCOME_P5M_KEY = 963;
    public static final int WELCOME_P5M_CONTAIN_KEY = 964;
    public static final int SECTION_ONE_SUB_ONE_KEY = 965;
    public static final int SECTION_ONE_SUB_ONE_CONTAIN_KEY = 966;
    public static final int SECTION_ONE_SUB_TWO_KEY = 967;
    public static final int SECTION_ONE_SUB_TWO_CONTAIN_KEY = 968;
    public static final int SECTION_ONE_TITLE_KEY = 969;
    public static final int SECTION_ONE_SUB_THREE_KEY = 970;
    public static final int SECTION_ONE_SUB_THREE_DETAIL_KEY = 971;
    public static final int SECTION_ONE_SUB_FOUR_KEY = 972;
    public static final int SECTION_ONE_SUB_FOUR_DETAIL_KEY = 973;
    public static final int SECTION_TWO_TITLE_KEY = 974;
    public static final int SECTION_TWO_SUB_ONE_KEY = 975;
    public static final int SECTION_TWO_SUB_ONE_DETAIL_KEY = 976;
    public static final int SECTION_TWO_SUB_TWO_KEY = 977;
    public static final int SECTION_TWO_SUB_TWO_DETAIL_KEY = 978;
    public static final int SECTION_TWO_SUB_THREE_KEY = 979;
    public static final int SECTION_TWO_SUB_THREE_DETAIL_KEY = 980;
    public static final int SECTION_TWO_SUB_FOUR_KEY = 981;
    public static final int SECTION_TWO_SUB_FOUR_DETAIL_KEY = 982;

    public static final int PLAN_DESCRIPTION_KEY = 983;
    public static final int DROP_IN_COST_KEY =984;
    public static final int SHOW_SELECTION_OPTIONS_KEY = 985;
    public static final int PLAN_DESCRIPTION_DROP_IN_KEY = 986;
    public static final int ON_BOARDING_DATA_KEY = 987;
    public static final int TESTIMONIALS_RIYADH_KEY = 988;
    public static final int BOOK_FIND_CLASS_KEY = 989;
    public static final int BOOK_OTHERS_KEY = 990;
    public static final int HOW_IT_WORKS_KEY = 991;
    public static final int PLAN_CLASS_KEY = 992;
    public static final int CONVERSTION_TEXT_KEY = 993;


    /* ------VALUES---------*/
    public static String BOOKED_VALUE = "Booked";
    public static String BOOK_VALUE = "Book";
    public static String FULL_VALUE = "Full";
    public static String WAITLISTED_VALUE = "Waitlisted";
    public static String WAITLIST_VALUE = "Waitlist";
    public static String JOIN_WAITLIST_VALUE = "Join Waitlist";
    public static String BOOK_WITH_FRIEND_VALUE = "Book with a friend";
    public static String SEARCH_BAR_TEXT_VALUE = "Search";
    public static String CLASS_CARD_TEXT_VALUE = "BOOK CLASS";
    public static String RECOMMENDED_FOR_YOU_VALUE = "Recommended for you";
    public static String BUY_CLASS_VALUE = "Buy Classes";
    public static String BUY_CLASS_COLOR_VALUE = "#3d85ea";
    public static String BOOK_IN_CLASS_VALUE = "Book Class";
    public static String SESSION_EXPIRED_VALUE = "Session Expired";
    public static String BOOKED_COLOR_VALUE = "#FF8C00";
    public static String BOOK_COLOR_VALUE = "#3d85ea";
    public static String FULL_COLOR_VALUE = "#FF0000";
    public static String RECOMMENDED_FOR_YOU_COLOR_VALUE = "#262626";
    public static String BOOK_WITH_FRIEND_COLOR_VALUE = "#3d85ea";
    public static String SESSION_EXPIRED_COLOR_VALUE = "#FF0000";
    public static String BOOK_WITH_FRIEND_BACKGROUND_COLOR_VALUE = "#FFFFFF";
    public static String INVITE_FRIENDS_VALUE = "Invite Friends";
    public static String ADD_TO_WISHLIST_VALUE = "Add to wishlist";
    public static String PAYMENT_PACKAGE_VALUE = "Book Classes";
    public static String PAYMENT_PENDING_VALUE = "View Payment History";
    public static String PAYMENT_FAILURE_VALUE = "View Payment History";
    public static String PAYMENT_CLASS_VALUE = "View Schedule";
    public static String GYM_VISIT_LIMIT_VALUE = "View gym visit limits";
    public static String SELECT_PLAN_TEXT_VALUE = "View Plan";
    public static String SELECT_PLAN_COLOR_VALUE = "#3d85ea";
    public static String BOOK_IN_CLASS_COLOR_VALUE = "#3d85ea";
    public static String GYM_VISIT_LIMIT_DETAIL_TEXT_VALUE = "Under each plan, there are limits to the number of times you can visit each gym. Check below for the number of time you can visit a gym per plan. Once the limit is reached, you may still visit your favorite gym by purchasing a single visit pass.";
    public static String MEMBERSHIP_OFFER_COLOR_VALUE = "#1FB257";
    public static String TESTIMONIALS_VALUE = "";
    public static String TESTIMONIALS_RIYADH_VALUE = "";
    public static String PACKAGE_TAGS_VALUE = "";
    public static String FAQ_VALUE = "";
    public static String WELCOME_P5M_VALUE = "Welcome to P5M";
    public static String WELCOME_P5M_CONTAIN_VALUE = "On P5M you can visit multiple gyms and do multiple activities using 1 membership ONLY!";
    public static String SECTION_ONE_SUB_ONE_VALUE = "Variety of activities";
    public static String SECTION_ONE_SUB_ONE_CONTAIN_VALUE = "With the P5M membership you can visit a swimming class today, crossfit tomorrow and yoga on the weekend. Each class at a different gym.";
    public static String SECTION_ONE_SUB_TWO_VALUE = "Visit 40 gyms with 1 membership";
    public static String SECTION_ONE_SUB_TWO_CONTAIN_VALUE = "Go to a different gym for every workout if you want!";
    public static String SECTION_ONE_TITLE_VALUE = "With the P5M membership you can:";
    public static String SECTION_ONE_SUB_THREE_VALUE = "Save 40%";
    public static String SECTION_ONE_SUB_THREE_DETAIL_VALUE = "If you generally purchase a single entry pass to a gym, you would save 40% by getting a package.Pay 30KWD for 5 classes instead of 50KWD!";
    public static String SECTION_ONE_SUB_FOUR_VALUE = "";
    public static String SECTION_ONE_SUB_FOUR_DETAIL_VALUE = "";
    public static String SECTION_TWO_TITLE_VALUE = "";
    public static String SECTION_TWO_SUB_ONE_VALUE = "";
    public static String SECTION_TWO_SUB_ONE_DETAIL_VALUE = "";
    public static String SECTION_TWO_SUB_TWO_VALUE = "";
    public static String SECTION_TWO_SUB_TWO_DETAIL_VALUE = "";
    public static String SECTION_TWO_SUB_THREE_VALUE = "";
    public static String SECTION_TWO_SUB_THREE_DETAIL_VALUE = "";
    public static String SECTION_TWO_SUB_FOUR_VALUE = "";
    public static String SECTION_TWO_SUB_FOUR_DETAIL_VALUE = "";

    public static String PLAN_DESCRIPTION_DROP_IN_VALUE = "";
    public static String PLAN_DESCRIPTION_VALUE = "";
    public static String DROP_IN_COST_VALUE = "true";
    public static String SHOW_SELECTION_OPTIONS_VALUE = "true";
    public static String ON_BOARDING_DATA_VALUE = "";
    public static String CHANNEL_LIST = "";
    public static String BOOK_FIND_CLASS_VALUE = "[{\"online_button_en\": \"online\", \"physical_button_en\": \"At-Gym\", \"online_button_ar\": \"online\", \"physical_button_ar\": \"At-Gym\"}]";
    public static String BOOK_OTHER_VALUE = "[{\"online_button_en\": \"online\", \"physical_button_en\": \"At-Gym\", \"online_button_ar\": \"online\", \"physical_button_ar\": \"At-Gym\"}]";
    public static String HOW_IT_WORKS_VALUE = "";
    public static String PLAN_CLASS_VALUES = "";
    public static String CONVERSTION_TEXT_VALUE = "";



}